export const comics = [
    {
      id: "1",
      imageUrl: "/assets/img/trending/image.png",
      title: "Solo Leveling",
      subtitle: "Thriller, Sci-fi",
      rating: 4,
      votes: 1029,
      description: "A young man rises from the depths of despair to the peak of power as the last survivor of the 'Dungeon' world.",
      type: "Webtoon",
      studios: "Redice Studio",
      airDate: "Mar 4, 2018 to present",
      status: "Airing",
      genre: "Action, Fantasy, Adventure",
      scores: "9.5 / 10",
      duration: "30 min/ep",
      quality: "HD",
      views: 15000,
      comments: 30,
      episodes: "12 / 12",
      tags: ["Thriller", "Sci-fi"],
      link: "/comic-detail/1",
    },
    {
      id: "2",
      imageUrl: "/assets/img/blog/details/image.png",
      title: "Omniscient Reader's Viewpoint",
      subtitle: "Horror, Action",
      rating: 4.5,
      votes: 2040,
      description: "A man becomes the main character in a world that follows a novel he read.",
      type: "Webtoon",
      studios: "Suiyobi no Gomi",
      airDate: "Nov 27, 2018 to present",
      status: "Airing",
      genre: "Action, Horror, Mystery",
      scores: "9.7 / 10",
      duration: "40 min/ep",
      quality: "HD",
      views: 20000,
      comments: 40,
      episodes: "15 / 15",
      tags: ["Horror", "Action"],
      link: "/comic-detail/2",
    },
    {
      id: "3",
      imageUrl: "/assets/img/anime/image.png",
      title: "SSS Class Suicide Hunter",
      subtitle: "Fantasy, Action",
      rating: 5,
      votes: 3020,
      description: "A man with no powers must survive in a deadly world of supernatural beings.",
      type: "Manga",
      studios: "Manta Comics",
      airDate: "Aug 19, 2020 to present",
      status: "Ongoing",
      genre: "Fantasy, Action, Adventure",
      scores: "9.8 / 10",
      duration: "25 min/ep",
      quality: "HD",
      views: 50000,
      comments: 100,
      episodes: "22 / 22",
      tags: ["Fantasy", "Action"],
      link: "/comic-detail/3",
    },
    // Thêm nhiều dữ liệu giả khác ở đây
  ];
  